sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge se-methods1
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network se-methods1 mongo
  - docker build -t se_methods1 .
  - docker run --network se-methods1 se_methods1